# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
# default: &default
#   adapter: sqlite3
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   timeout: 10000

  
# production:
#   <<: *default
#   database: db/anabtate_tiendita_production_latest.db


# development:
#   <<: *default
#   database: db/anabtate_tiendita_production_latest.db



development:
   adapter: postgresql
   encoding: unicode
   database: skygaze_development
   pool: 5
   username: skygaze
   password: skygaze2020
   timeout: 5000
   host: localhost

test:
   adapter: postgresql
   encoding: unicode
   database: skygaze_test
   pool: 5
   username: skygaze
   password: skygaze2020
   timeout: 5000
   host: localhost

production:
   adapter: postgresql
   encoding: utf8
   database: skygaze_production
   pool: 5
   username: skygaze
   password: skygaze2020
   timeout: 5000
   host: localhost



   